[2024-07-13T02:01:30.308+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-13T02:01:30.325+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dnd_RF_classification.hyperopt_experiment manual__2024-07-13T02:01:21.823071+00:00 [queued]>
[2024-07-13T02:01:30.331+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dnd_RF_classification.hyperopt_experiment manual__2024-07-13T02:01:21.823071+00:00 [queued]>
[2024-07-13T02:01:30.331+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-13T02:01:30.349+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): hyperopt_experiment> on 2024-07-13 02:01:21.823071+00:00
[2024-07-13T02:01:30.360+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=65) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-13T02:01:30.361+0000] {standard_task_runner.py:63} INFO - Started process 68 to run task
[2024-07-13T02:01:30.362+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dnd_RF_classification', 'hyperopt_experiment', 'manual__2024-07-13T02:01:21.823071+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/sklearn_ml_pipeline.py', '--cfg-path', '/tmp/tmpnmaxm10t']
[2024-07-13T02:01:30.363+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask hyperopt_experiment
[2024-07-13T02:01:30.410+0000] {task_command.py:426} INFO - Running <TaskInstance: dnd_RF_classification.hyperopt_experiment manual__2024-07-13T02:01:21.823071+00:00 [running]> on host 64ae5f811ff0
[2024-07-13T02:01:30.496+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dnd_RF_classification' AIRFLOW_CTX_TASK_ID='hyperopt_experiment' AIRFLOW_CTX_EXECUTION_DATE='2024-07-13T02:01:21.823071+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-13T02:01:21.823071+00:00'
[2024-07-13T02:01:30.498+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-13T02:01:30.848+0000] {logging_mixin.py:188} WARNING - 2024/07/13 02:01:30 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
[2024-07-13T02:01:30.850+0000] {logging_mixin.py:188} WARNING - 2024/07/13 02:01:30 INFO mlflow.store.db.utils: Updating database tables
[2024-07-13T02:01:31.339+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-13T02:01:31.369+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-13T02:01:31.378+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
